# Generated by Django 6.0 on 2025-12-05 17:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250, unique=True)),
                ("bio_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScrapeJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("quotes_fetched", models.IntegerField(default=0)),
                ("quotes_saved", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("initiator", models.CharField(default="api", max_length=40)),
                ("meta", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScrapeSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("base_url", models.URLField(max_length=500)),
                (
                    "start_path",
                    models.CharField(blank=True, default="/", max_length=500),
                ),
                (
                    "quote_selector",
                    models.CharField(
                        help_text="CSS or XPath for quote text", max_length=500
                    ),
                ),
                (
                    "author_selector",
                    models.CharField(
                        help_text="CSS or XPath for author name", max_length=500
                    ),
                ),
                (
                    "pagination_selector",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CSS/XPath for next page link (optional)",
                        max_length=500,
                    ),
                ),
                (
                    "max_pages",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "rate_limit_ms",
                    models.PositiveIntegerField(
                        default=500, help_text="Delay between requests in milliseconds"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScrapeError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                ("error_type", models.CharField(max_length=120)),
                ("message", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="scraper_api.scrapejob",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="scrapejob",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="scraper_api.scrapesite",
            ),
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("source_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("hash", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="scraper_api.author",
                    ),
                ),
                (
                    "saved_by_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_quotes",
                        to="scraper_api.scrapejob",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="scraper_api.scrapesite",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["author"], name="scraper_api_author__63ec6d_idx"
                    ),
                    models.Index(
                        fields=["site"], name="scraper_api_site_id_bc7392_idx"
                    ),
                ],
            },
        ),
    ]
